'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import TasteIQBrandLogo from '@/components/food-brand/TasteIQBrandLogo';
import { useStartFreeNav } from '@/components/layout/StartFreeNavContext';
import { FOODS_SITE_URL } from '@/lib/site-urls';
import PrototypeFooter from './PrototypeFooter';
import StartFreeModal from './StartFreeModal';

const manifestoBlocks = [
  {
    num: '01',
    label: 'What we believe',
    title: (
      <>
        The right number of <em>subscriptions</em> for software is zero.
      </>
    ),
    paragraphs: [
      'Restaurants do not have a software cost problem. They have a margin problem — squeezed at the top by 30% aggregator commissions, and at the bottom by labor and rent. Selling them another monthly subscription was always strange: it taxed the smallest line item on their P&L while doing nothing about the largest.',
      'We charge nothing for the software. We earn when our customers earn — through payments, through the direct orders we generate for them, through a small slice of the demand-side flows we replace. This is not a pricing trick. It is a different relationship with our customer, and it is only possible because AI has collapsed the cost of building and supporting software per-business. Free is the natural endpoint. Everyone will arrive here. We are starting here.',
    ],
  },
  {
    num: '02',
    label: 'What we build',
    title: (
      <>
        The right number of <em>UIs</em> for a restaurant is one — its own.
      </>
    ),
    paragraphs: [
      'A cloud kitchen running eight brands and a fine-dining omakase do not run the same business. They should not run the same software. We ship a set of well-defined primitives — menu, order, inventory, customer, payment, state machines — and let an agent shape the interface to each business.',
      "The pizza place doesn't see table management. The bar sees tab logic in the hero card. The dhaba sees Hindi-first voice ordering. None of these screens were drawn by a designer. They were generated by observing how each operator works. Software stops being a thing the operator adapts to. It becomes a thing that adapts to the operator.",
    ],
  },
  {
    num: '03',
    label: 'Where it goes',
    title: (
      <>
        The right way to be discovered is by an <em>agent</em>, not an algorithm.
      </>
    ),
    paragraphs: [
      'For fifteen years, restaurants discovered customers through search, then through aggregators, then through the algorithmic feeds of two or three platforms that took an ever-larger share of their revenue. The next platform shift has already started. Customers are beginning to order through agents — through ChatGPT, through Claude, through whatever assistant they live inside.',
      'To be transactable by an agent, a restaurant needs its menu, its inventory, its hours, and its rules to be machine-readable in real time. That requires a system of record. We are building that system. The restaurants on TasteIQ will be the first that agents can actually buy from.',
    ],
  },
];

export default function VisionPage() {
  const [modalOpen, setModalOpen] = useState(false);
  const { registerStartFree } = useStartFreeNav();

  useEffect(() => {
    registerStartFree(() => setModalOpen(true));
    return () => registerStartFree(null);
  }, [registerStartFree]);

  useEffect(() => {
    if (typeof window !== 'undefined' && window.location.hash === '#start') {
      setModalOpen(true);
    }
  }, []);

  return (
    <>
      <section className="vision-hero">
        <div className="vision-hero-art" aria-hidden="true">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/prototype/vision-hero.svg"
            alt=""
            className="absolute inset-0 w-full h-full object-cover"
          />
          <div className="vision-hero-fade" />
        </div>
        <div className="vision-hero-wrap">
          <TasteIQBrandLogo hero className="vision-hero-brand" />
          <h1 className="vision-hero-h1">
            The operating system <em>restaurants</em> deserve.
          </h1>
          <p className="vision-hero-sub">
            Free software. One UI per restaurant, shaped by an agent. Transactable by the assistants
            your customers already live in.
          </p>
          <div className="vision-hero-cta">
            <button type="button" className="btn btn-primary" onClick={() => setModalOpen(true)}>
              Start free
            </button>
            <a href="#manifesto" className="btn btn-ghost">
              Read the vision
            </a>
          </div>
        </div>
      </section>

      <section className="manifesto" id="manifesto">
        <div className="m-wrap">
          {manifestoBlocks.map((block) => (
            <article key={block.num} className="m-block">
              <div className="m-eyebrow">
                <b>{block.num}</b>
                <span>{block.label}</span>
                <span className="m-eyebrow-line" />
              </div>
              <h3 className="m-h">{block.title}</h3>
              {block.paragraphs.map((p, i) => (
                <p key={i} className="m-body">
                  {p}
                </p>
              ))}
            </article>
          ))}
        </div>
      </section>

      <section className="closing" id="start">
        <p className="closing-q">
          An operating system that costs nothing, fits one restaurant, and is found by the next
          generation of buyers.
        </p>
        <div className="closing-cta">
          <button type="button" className="btn btn-primary" onClick={() => setModalOpen(true)}>
            Start free
          </button>
          <a href={FOODS_SITE_URL} className="btn btn-ghost" rel="noopener noreferrer">
            Explore TasteIQ Foods
          </a>
        </div>
      </section>

      <PrototypeFooter />
      <StartFreeModal open={modalOpen} onClose={() => setModalOpen(false)} />
    </>
  );
}
